### ISSUE TITLE
.Net Core Version

### ISSUE THREAD

**Issue by samcov** [MicrosoftEdge/pushnotifications-demo#1]
Thanks for the Node sample, it's one of two environments I use regularly.

The other is asp.net core.

Is there a plan to have a demo for core?

**Comment by mark-szabo** [comment]
Hi @samcov 
we are happy to announce that the ASP.NET Core 2.0 version of this sample is ready! You can reach it here: https://github.com/MicrosoftEdge/pushnotifications-demo-aspnetcore

**Comment by samcov** [comment]
Great, I'll have a look!
